services:
  frontend:
    container_name: xaiml_p3_frontend
    image: xaiml_p3_frontend:latest
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./frontend/app:/app/app:cached
      - ./frontend/public:/app/public:cached
    ports:
      - '3000:3000'
      - '3010:3010'
    depends_on:
      - backend
    environment:
      - NODE_ENV=development
      # - CHOKIDAR_USEPOLLING=true

  backend:
    container_name: xaiml_p3_backend
    image: xaiml_p3_backend:latest
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
      target: development
      args:
        PORT: 8080
    restart: unless-stopped
    environment:
      - TRACKING_DIR=/application_root/data/nba_tracking_data
      - DATA_DIR=/application_root/data
      - EMBEDDINGS_DIR=/application_root/data/embeddings
    volumes:
      - ./backend/src/server:/application_root/server:cached
      - ./backend/data:/application_root/data:cached
    ports:
      - '8080:8080'
volumes:
  node_modules: {}
