services:
  frontend:
    container_name: xaiml_p3_frontend
    image: xaiml_p3_frontend:latest
    build:
      context: ./frontend/
      dockerfile: ./Dockerfile
      # target: base
    volumes:
      - ./frontend/http:/http
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    container_name: xaiml_p3_backend
    image: xaiml_p3_backend:latest
    build:
      context: ./backend/
      dockerfile: ./Dockerfile
      target: development
      args:
        PORT: 8080
    volumes:
      - ./backend/http:/http
    ports:
      - '8080:8080'
