frontend:
  image:
    repository: xaiml_p3_frontend
    tag: latest
    # Ensure we use the production target
    buildArgs:
      target: production
    # cmd: ["your_cmd"]
    # args: ["an", "array", "of", "values"]

  # Only production port
  port: 3000

  # Path for health check.
  health: '/'

  # Define extra environment variables for your application
  extraEnv: |
    - name: NODE_ENV
      value: "production"

  url: null

  # Dependencies
  dependencies:
    - backend

backend:
  image:
    repository: xaiml_p3_backend
    tag: latest
    # Ensure we use the production target and set PORT
    buildArgs:
      target: production
      PORT: 8080
    # cmd: ["your_cmd"]
    # args: ["an", "array", "of", "values"]

  port: 8080

  # Path for health check.
  health: '/'

  # Security context for the app-user created in Dockerfile
  securityContext:
    runAsUser: 1001
    runAsGroup: 1001

  # Define extra environment variables for your application
  extraEnv: |
    - name: DATASET_DIR
      value: "/application_root/data/nba_tracking_data"
    - name: PYTHONUNBUFFERED
      value: "1"
    - name: PYTHONDONTWRITEBYTECODE
      value: "1"
    - name: PYTHONPATH
      value: "/application_root/"

  url: null

  volumes:
    - name: data-volume
      hostPath:
        path: ./backend/data
      mountPath: /application_root/data
